from turtle import Turtle, Screen

s1=Screen()
tom=Turtle()
tom.shape("turtle")
tom.speed("fast")
# tom.color("black","pink")
# tom.begin_fill()
# tom.circle(100)
# tom.end_fill()
# tom.right(90)
# tom.hideturtle()
# tom.penup()
# tom.forward(100)
# tom.pendown()
# tom.pensize(10)
# tom.color("orange","orange")
# tom.begin_fill()
# tom.circle(70)
# tom.end_fill()
# print(tom.pos())
# tom.penup()
# tom.goto(-100,-100)
# tom.pendown()
# tom.showturtle()

# tom.fillcolor("green")
# print(tom.pencolor())
#circle

tom.left(140)
tom.penup()
tom.goto(-180,180)
tom.pendown()
tom.pensize(5)
tom.color("yellow","yellow")
tom.begin_fill()
tom.circle(60)
tom.end_fill()

## triangle
tom.penup()
tom.goto(-180,-180)
tom.pendown()
tom.pensize(5)
tom.color("green","green")
tom.begin_fill()
tom.right(20)
tom.forward(100)
tom.left(120)
tom.forward(100)
tom.left(120)
tom.forward(100)
tom.end_fill()
#square
tom.penup()
tom.goto(160,100)
tom.pendown()
tom.pensize(5)
tom.color("red","red")
tom.begin_fill()
for _ in range(4):
    tom.forward(100)
    tom.left(90)
tom.end_fill()

# pentagon
tom.penup()
tom.goto(160,-160)
tom.pendown()
tom.pensize(5)
tom.color("blue","blue")
tom.begin_fill()
for _ in range(5):
    tom.forward(100)
    tom.left(72)
tom.end_fill()


s1.mainloop()
